<?php
/**
 * Functions for handling the Products section of the Vendor Dashboard.
 */
if ( ! defined( 'WPINC' ) ) { die; }

/** Get vendor products query - Updated for Filtering & Search */
function vdb_get_vendor_products( $vendor_id ) {
    // --- START: Filtering & Search ---
    $search_query = isset( $_GET['s'] ) ? sanitize_text_field( wp_unslash( $_GET['s'] ) ) : ''; // Added wp_unslash
    $status_filter = isset( $_GET['status'] ) ? sanitize_key( $_GET['status'] ) : 'any'; // Default to 'any' or specific like 'publish,draft,pending'
    $category_filter = isset( $_GET['category'] ) ? absint( $_GET['category'] ) : 0;
    $stock_filter = isset($_GET['stock_status']) ? sanitize_key($_GET['stock_status']) : '';

    $args = array(
        'post_type' => 'product', 'author' => $vendor_id, 'posts_per_page' => 20,
        'orderby' => 'date', 'order' => 'DESC', 's' => $search_query,
    );
    if ($status_filter !== 'any' && !empty($status_filter)) { $allowed_statuses = array('publish', 'draft', 'pending', 'private'); if (in_array($status_filter, $allowed_statuses)) { $args['post_status'] = $status_filter; } else { $args['post_status'] = array('publish', 'draft', 'pending'); } } else { $args['post_status'] = array('publish', 'draft', 'pending'); }
    if ($category_filter > 0) { if ( ! isset( $args['tax_query'] ) ) { $args['tax_query'] = array(); } $args['tax_query'][] = array( 'taxonomy' => 'product_cat', 'field' => 'term_id', 'terms' => $category_filter, ); }
    if (!empty($stock_filter) && in_array($stock_filter, ['instock', 'outofstock'])) { if ( ! isset( $args['meta_query'] ) ) { $args['meta_query'] = array(); } $args['meta_query'][] = array( 'key' => '_stock_status', 'value' => $stock_filter, 'compare' => '=', ); }
    $args['paged'] = get_query_var('paged') ? get_query_var('paged') : 1;
    // --- END: Filtering & Search ---
    return new WP_Query( $args );
}

/** Render the vendor's product list - Updated with Filters, Search, Thumbnails */
function vdb_render_product_list( $vendor_id ) {
    $current_search = isset( $_GET['s'] ) ? esc_attr( wp_unslash( $_GET['s'] ) ) : ''; $current_status = isset( $_GET['status'] ) ? esc_attr( $_GET['status'] ) : 'any'; $current_category = isset( $_GET['category'] ) ? absint( $_GET['category'] ) : 0; $current_stock = isset($_GET['stock_status']) ? esc_attr($_GET['stock_status']) : '';
    $products_query = vdb_get_vendor_products( $vendor_id );
    ?>
    <h4><?php esc_html_e( 'Your Products', 'vendor-dashboard' ); ?></h4>
    <div class="vdb-list-filters"><form method="GET" action=""><?php foreach ($_GET as $key => $value): if ($key !== 's' && $key !== 'status' && $key !== 'category' && $key !== 'stock_status' && $key !== 'paged'): ?><input type="hidden" name="<?php echo esc_attr($key); ?>" value="<?php echo esc_attr(wp_unslash($value)); ?>" /><?php endif; endforeach; ?><span class="vdb-filter-item"><label for="vdb-filter-status" class="screen-reader-text"><?php esc_html_e('Filter by status', 'vendor-dashboard'); ?></label><select name="status" id="vdb-filter-status"><option value="any" <?php selected($current_status, 'any'); ?>><?php esc_html_e('All Statuses', 'vendor-dashboard'); ?></option><option value="publish" <?php selected($current_status, 'publish'); ?>><?php esc_html_e('Published', 'vendor-dashboard'); ?></option><option value="draft" <?php selected($current_status, 'draft'); ?>><?php esc_html_e('Draft', 'vendor-dashboard'); ?></option><option value="pending" <?php selected($current_status, 'pending'); ?>><?php esc_html_e('Pending Review', 'vendor-dashboard'); ?></option></select></span><span class="vdb-filter-item"><label for="vdb-filter-category" class="screen-reader-text"><?php esc_html_e('Filter by category', 'vendor-dashboard'); ?></label><?php wp_dropdown_categories( array( 'show_option_all' => __( 'All Categories', 'vendor-dashboard' ), 'taxonomy' => 'product_cat', 'name' => 'category', 'orderby' => 'name', 'selected' => $current_category, 'hierarchical' => true, 'depth' => 1, 'show_count' => false, 'hide_empty' => false, 'value_field' => 'term_id', 'id' => 'vdb-filter-category' ) ); ?></span><span class="vdb-filter-item"><label for="vdb-filter-stock" class="screen-reader-text"><?php esc_html_e('Filter by stock status', 'vendor-dashboard'); ?></label><select name="stock_status" id="vdb-filter-stock"><option value="" <?php selected($current_stock, ''); ?>><?php esc_html_e('Any Stock Status', 'vendor-dashboard'); ?></option><option value="instock" <?php selected($current_stock, 'instock'); ?>><?php esc_html_e('In Stock', 'vendor-dashboard'); ?></option><option value="outofstock" <?php selected($current_stock, 'outofstock'); ?>><?php esc_html_e('Out of Stock', 'vendor-dashboard'); ?></option></select></span><span class="vdb-filter-item vdb-search-item"><label for="vdb-search-input" class="screen-reader-text"><?php esc_html_e('Search Products', 'vendor-dashboard'); ?></label><input type="search" id="vdb-search-input" name="s" value="<?php echo $current_search; ?>" placeholder="<?php esc_attr_e('Search products...', 'vendor-dashboard'); ?>" /></span><span class="vdb-filter-item"><input type="submit" class="button button-secondary" value="<?php esc_attr_e('Filter', 'vendor-dashboard'); ?>" /></span></form></div>
    <button class="button vdb-add-new-product"><?php esc_html_e( 'Add New Product', 'vendor-dashboard' ); ?></button>
    <table class="vdb-table widefat striped"><thead><tr><th class="vdb-col-thumb"></th><th><?php esc_html_e('Name', 'vendor-dashboard'); ?></th><th><?php esc_html_e('Status', 'vendor-dashboard'); ?></th><th><?php esc_html_e('Price', 'vendor-dashboard'); ?></th><th><?php esc_html_e('Stock', 'vendor-dashboard'); ?></th><th><?php esc_html_e('Actions', 'vendor-dashboard'); ?></th></tr></thead><tbody>
            <?php if ( $products_query->have_posts() ) : while ( $products_query->have_posts() ) : $products_query->the_post(); $product_id = get_the_ID(); $product = wc_get_product( $product_id ); if ( ! $product ) continue; $status_slug = $product->get_status(); $status_label = ucfirst($status_slug); switch ($status_slug){case 'publish':$status_label=__('Published','vendor-dashboard');break;case 'draft':$status_label=__('Draft','vendor-dashboard');break;case 'pending':$status_label=__('Pending Review','vendor-dashboard');break;} $stock_quantity_display = '-'; if ( $product->managing_stock() ) {$stock_qty=$product->get_stock_quantity();$stock_quantity_display=is_null($stock_qty) ? '-' : wc_stock_amount($stock_qty);}else{$stock_quantity_display=$product->get_stock_status()==='instock'?__('In stock','vendor-dashboard'):__('Out of stock','vendor-dashboard');} $thumbnail_html = $product->get_image('thumbnail', array('style'=>'width: 50px; height: auto; border: 1px solid #eee; vertical-align: middle;'), false); if (empty($thumbnail_html)) { $thumbnail_html = '<span class="vdb-no-thumb">'.__('No img','vendor-dashboard').'</span>'; } ?>
            <tr><td class="vdb-col-thumb"><?php echo $thumbnail_html; ?></td><td><?php the_title(); ?></td><td><?php echo esc_html( $status_label ); ?></td><td><?php echo wp_kses_post( $product->get_price_html() ?: '-' ); ?></td><td><?php echo esc_html( $stock_quantity_display ); ?></td><td><button class="button vdb-edit-product" data-product-id="<?php echo esc_attr( $product_id ); ?>"><?php esc_html_e( 'Edit', 'vendor-dashboard' ); ?></button></td></tr>
            <?php endwhile; else : ?><tr> <td colspan="6"><?php esc_html_e( 'No products found matching your criteria.', 'vendor-dashboard' ); ?></td> </tr><?php endif; ?></tbody></table>
    <div class="vdb-pagination"><?php $base_url = remove_query_arg( 'paged', esc_url_raw( add_query_arg( null, null ) ) ); $big = 999999999; echo paginate_links( array( 'base' => $base_url . '%_%', 'format' => '&paged=%#%', 'current' => max( 1, get_query_var('paged') ), 'total' => $products_query->max_num_pages, 'prev_text' => __('« Previous'), 'next_text' => __('Next »'), 'add_args' => false, ) ); ?></div>
    <?php wp_reset_postdata(); ?>
    <?php
}

/** Render the product editor form structure - Attributes Section Removed */
function vdb_render_product_editor_form() {
     $nonce = wp_create_nonce('vdb_save_product_nonce');
    ?>
    <div id="vdb-product-editor-container" style="display: none; margin-top: 20px; padding: 15px; border: 1px solid #ccc; background: #f9f9f9;">
        <h3><?php esc_html_e( 'Edit Product', 'vendor-dashboard' ); ?></h3>
        <form id="vdb-product-editor-form" method="post" enctype="multipart/form-data">
            <input type="hidden" name="vdb_product_id" id="vdb_edit_product_id" value="">
            <input type="hidden" name="vdb_save_product_nonce" value="<?php echo esc_attr($nonce); ?>">
            <input type="hidden" name="vdb_remove_featured_image" id="vdb_remove_featured_image_flag" value="0">

            <?php // --- Form Sections (General, Data, Shipping, Organization, Images) --- ?>
            <div class="vdb-form-section"><h4><?php esc_html_e('General', 'vendor-dashboard'); ?></h4><p><label for="vdb_edit_title"><?php esc_html_e('Product Name','vendor-dashboard');?><br><input type="text" name="vdb_title" id="vdb_edit_title" required class="regular-text"></label></p><p><label for="vdb_edit_description"><?php esc_html_e('Description','vendor-dashboard');?><br><textarea name="vdb_description" id="vdb_edit_description" rows="5" class="large-text"></textarea></label></p><p><label for="vdb_edit_short_description"><?php esc_html_e('Short Description','vendor-dashboard');?><br><textarea name="vdb_short_description" id="vdb_edit_short_description" rows="3" class="large-text"></textarea></label></p></div>
            <div class="vdb-form-section"><h4><?php esc_html_e('Product Data', 'vendor-dashboard'); ?></h4><p><label for="vdb_edit_sku"><?php esc_html_e( 'SKU', 'vendor-dashboard' ); ?><br><input type="text" name="vdb_sku" id="vdb_edit_sku" class="regular-text"></label></p><p><label for="vdb_edit_reg_price"><?php esc_html_e('Regular Price','vendor-dashboard');?> (<?php echo get_woocommerce_currency_symbol(); ?>)<br><input type="text" inputmode="decimal" name="vdb_regular_price" id="vdb_edit_reg_price" class="short wc_input_price"></label></p><p><label for="vdb_edit_sale_price"><?php esc_html_e( 'Sale Price', 'vendor-dashboard' ); ?> (<?php echo get_woocommerce_currency_symbol(); ?>)<br><input type="text" inputmode="decimal" name="vdb_sale_price" id="vdb_edit_sale_price" class="short wc_input_price" placeholder="<?php esc_attr_e('Optional','vendor-dashboard');?>"></label></p><p><label for="vdb_edit_stock"><?php esc_html_e('Stock Quantity','vendor-dashboard');?><br><input type="number" step="1" name="vdb_stock_quantity" id="vdb_edit_stock" class="short wc_input_stock" placeholder="<?php esc_attr_e('Leave blank to disable stock management','vendor-dashboard');?>"></label></p></div>
            <div class="vdb-form-section"><h4><?php esc_html_e('Shipping', 'vendor-dashboard'); ?></h4><p><label for="vdb_edit_weight"><?php esc_html_e('Weight', 'vendor-dashboard'); ?> (<?php echo esc_html( get_option( 'woocommerce_weight_unit' ) ); ?>)</label><br><input type="text" inputmode="decimal" name="vdb_weight" id="vdb_edit_weight" class="short wc_input_decimal"></p><p><label><?php esc_html_e('Dimensions', 'vendor-dashboard'); ?> (<?php echo esc_html( get_option( 'woocommerce_dimension_unit' ) ); ?>)</label><br><input type="text" inputmode="decimal" name="vdb_length" id="vdb_edit_length" placeholder="<?php esc_attr_e('Length', 'vendor-dashboard');?>" class="short wc_input_decimal" style="margin-right: 5px;"><input type="text" inputmode="decimal" name="vdb_width" id="vdb_edit_width" placeholder="<?php esc_attr_e('Width', 'vendor-dashboard');?>" class="short wc_input_decimal" style="margin-right: 5px;"><input type="text" inputmode="decimal" name="vdb_height" id="vdb_edit_height" placeholder="<?php esc_attr_e('Height', 'vendor-dashboard');?>" class="short wc_input_decimal"></p><p><label for="vdb_edit_shipping_class"><?php esc_html_e('Shipping Class','vendor-dashboard');?></label><br><select name="vdb_shipping_class" id="vdb_edit_shipping_class" class="regular-text"><option value="-1"><?php esc_html_e('No shipping class', 'vendor-dashboard'); ?></option></select></p></div>
            <div class="vdb-form-section"><h4><?php esc_html_e('Organization', 'vendor-dashboard'); ?></h4><p><label for="vdb_edit_category"><?php esc_html_e('Product Category','vendor-dashboard');?></label><br><select name="vdb_category" id="vdb_edit_category" class="regular-text"><option value="0"><?php esc_html_e('-- Select a Category --', 'vendor-dashboard'); ?></option></select></p><p><label for="vdb_edit_tags"><?php esc_html_e('Product Tags','vendor-dashboard');?></label><br><input type="text" name="vdb_tags" id="vdb_edit_tags" class="regular-text" placeholder="<?php esc_attr_e('Comma-separated tags', 'vendor-dashboard'); ?>"></p></div>
            <div class="vdb-form-section"><h4><?php esc_html_e('Images', 'vendor-dashboard'); ?></h4><p><label for="vdb_edit_featured_image"><?php esc_html_e( 'Featured Image', 'vendor-dashboard' ); ?></label><br><span id="vdb-current-image-preview" style="margin-bottom: 10px; display: inline-block; position: relative; min-height: 50px; min-width: 50px; vertical-align: top;"></span><div id="vdb-new-image-preview" style="margin-bottom: 10px; max-width: 150px; display: none; vertical-align: top;"></div><input type="file" name="vdb_featured_image" id="vdb_edit_featured_image" accept="image/jpeg, image/png, image/gif"><small style="display: block; margin-top: 5px;"><?php esc_html_e( 'Upload a new image to replace the current one.', 'vendor-dashboard' ); ?></small></p><p><label><?php esc_html_e( 'Product Gallery', 'vendor-dashboard' ); ?></label><br><div id="vdb-current-gallery-preview" style="margin-bottom: 10px; display: flex; flex-wrap: wrap; gap: 10px; min-height: 50px; background: rgba(0,0,0,0.02); border: 1px dashed #eee; padding: 5px;"></div><label for="vdb_edit_gallery_images" style="font-weight: normal; margin-top: 10px; display: block;"><?php esc_html_e( 'Add Images to Gallery:', 'vendor-dashboard' ); ?></label><div id="vdb-new-gallery-preview" style="margin-bottom: 10px; display: flex; flex-wrap: wrap; gap: 10px; max-width: 100%;"></div><input type="file" name="vdb_gallery_images[]" id="vdb_edit_gallery_images" accept="image/jpeg, image/png, image/gif" multiple><small style="display: block; margin-top: 5px;"><?php esc_html_e( 'Select one or more images to add. Click (x) on existing images to remove them on save.', 'vendor-dashboard' ); ?></small></p></div>

            <?php // --- Attributes Section REMOVED --- ?>

            <p style="margin-top: 20px; border-top: 1px solid #eee; padding-top: 15px;"><button type="submit" class="button button-primary vdb-save-product"><?php esc_html_e( 'Save Product', 'vendor-dashboard' ); ?></button><button type="button" class="button vdb-cancel-edit"><?php esc_html_e( 'Cancel', 'vendor-dashboard' ); ?></button></p>
            <div class="vdb-editor-notice" style="display: none; margin-top: 10px;"></div>
        </form>
    </div>
    <?php
}
?>